version: '3.8'

services:
  # Application service for production
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acquitions-app-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Production DATABASE_URL should come from secrets/env file
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - ARCJET_KEY=${ARCJET_KEY}
    env_file:
      - .env.production
    volumes:
      # Only mount logs in production
      - ./logs:/app/logs
    networks:
      - acquitions-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})\""]
      interval: 30s
      timeout: 10s
      start-period: 40s
      retries: 3

networks:
  acquitions-network:
    driver: bridge
